# 767398153139.dkr.ecr.ap-south-1.amazonaws.com/bootcampflask
name: day-3 Build-Push

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'day3/**' 
  #     - '.github/workflows/build-push-day3.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  
    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 767398153139.dkr.ecr.ap-south-1.amazonaws.com
    - name: Build, Tag, and Push Docker Image
      run: |
        cd day3/src
        docker build -t 767398153139.dkr.ecr.ap-south-1.amazonaws.com/bootcampflask:day3 day3/src/ 
        docker push 767398153139.dkr.ecr.ap-south-1.amazonaws.com/bootcampflask:day3
        #updated
